name: "qwen3_evals"
ckpt_dir: /raid/user_data/rsadhukh/checkpoints/olmo2-1b-stage1-token1T
dump_dir: logs/olmo3_evals
model_type: olmo3
generator:
  max_tokens: 16384
  dtype: bf16
  temperature: 0.0
  top_p: 0.95
  show_progress: true

harness:
    tasks:
        - task: hellaswag
          dataset_path: /data/rsadhukh/eval_data/hellaswag
        - task: boolq
          dataset_path: /data/rsadhukh/eval_data/super_glue
        - task: piqa
          dataset_path: /data/rsadhukh/eval_data/piqa
        - task: winogrande
          dataset_path: /data/rsadhukh/eval_data/winogrande
        - task: openbookqa
          dataset_path: /data/rsadhukh/eval_data/openbookqa
        - task: arc_easy
          dataset_path: /data/rsadhukh/eval_data/ai2_arc
        - task: arc_challenge
          dataset_path: /data/rsadhukh/eval_data/ai2_arc
        - task: race
          dataset_path: /data/rsadhukh/eval_data/race
        - task: mmlu
          dataset_path: /data/rsadhukh/eval_data/mmlu
        - task: gsm8k
          dataset_path: /data/rsadhukh/eval_data/gsm8k
        - task: mbpp
          dataset_path: /data/rsadhukh/eval_data/mbpp
        - task: humaneval
          dataset_path: /data/rsadhukh/eval_data/humaneval
        # - task: bbh
        #   dataset_path: /data/rsadhukh/eval_data/bbh
        # - task: coqa
        #   dataset_path: /data/rsadhukh/eval_data/coqa
        # - task: squad_v2
        #   dataset_path: /data/rsadhukh/eval_data/squad_v2
    confirm_run_unsafe_code: true
    batch_size: 64
validation: null

