dump_dir: logs/debug
name: "longcat-1B-midfine"
model_type: olmo3
steps: 50_000
probe_freq: 100
seed: 777
grad_acc_steps: 2

optim:
    scheduler: "linear"
    lr: 7.44e-5
    weight_decay: 0.1
    warmup: 0
    lr_min_ratio: 0.0
    clip: 1.0

ngram_lr: 3e-4
ngram_weight_decay: 1e-4
ngram_lr_min_ratio: 0
ngram_warmup: 1000

distributed:
    fsdp_type: full_shard
    compile: true
    model_dtype: bf16
    matmul_allow_tf32: false
    selective_activation_checkpointing: false
    tp_size: 1
    stem_parallel_size: 2

model:
    dim: 2048
    ffn_dim_multiplier: 1.5
    multiple_of: 256
    n_layers: 16
    n_heads: 16
    n_kv_heads: 16
    head_dim: 128
    weight_tying: false
    init_base_std: 0.02
    init_std_factor: disabled
    norm_eps: 1.0e-6
    max_seqlen: 4096
    vocab_size: 100352
    rope_theta: 500000.0
    rope_scaling: null
    pad_token_id: 100277
    eos_token_id: 100257
    emb_neighbor_num: 3
    emb_split_num: 2
    ngram_vocab_size_ratio: 16
    ngram_embeddings_zero_reset: false
    

data:
    root_dir: /dev/shm/dolmino-mix_shuffled
    sources:
        common_crawl-high-quality: 7.776233
        cranecode: 4.971690
        cranemath: 3.076499
        dolmino-math: 9.475957
        dolmino_1-flan: 6.288976
        gemini-reasoning-traces: 0.036162
        general_reasoning_mix: 0.311049
        code-meta-reasoning: 0.1694
        # llama_nemotron-reasoning-traces: 1.234568
        math-meta-reasoning: 0.170397
        megamatt: 1.372526
        nemotron-synth-qa: 4.504267
        olmocr_science_pdfs: 0.509917
        openthoughts2: 0.170822
        program_verifiable: 0.067139
        qwq-reasoning-traces: 0.170397
        reddit_to_flashcards: 42.918011
        stack_edu: 6.883879
        stem-heavy-crawl: 2.349868
        tulu-3-sft: 0.616150
        wiki_to_rcqa: 6.926372
    node_local: false
    batch_size: 8
    prefetch_size: 1024
    seq_len: 4096
    n_views: 2
    load_async: true
    add_bos: true
    add_eos: true
    track_packed_source_mixture: true
    tokenizer:
        name: huggingface
        path: checkpoints/olmo2-1b-stage1-token1T

profiling:
    run: true

checkpoint:
    # Student initialization checkpoint (typically prepared by prepare_stem_checkpoint.py)
    init_ckpt_path: checkpoints/olmo2-1b-stem-1T-init
    dump:
        every: 10000
        keep: 1
    eval:
        every: 5000
        keep: 1

logging:
    freq: 10
    wandb:
        project: "stem"
        name: "longcat-1B-midfine"

eval:
    generator:
        max_tokens: 16384
        dtype: bf16
        temperature: 1.0
        top_p: 0.95
    harness:
        tasks:
            - task: hellaswag
              dataset_path: /data/rsadhukh/eval_data/hellaswag
            - task: boolq
              dataset_path: /data/rsadhukh/eval_data/super_glue
            - task: piqa
              dataset_path: /data/rsadhukh/eval_data/piqa
            - task: winogrande
              dataset_path: /data/rsadhukh/eval_data/winogrande
            - task: openbookqa
              dataset_path: /data/rsadhukh/eval_data/openbookqa
            - task: arc_easy
              dataset_path: /data/rsadhukh/eval_data/ai2_arc
            - task: arc_challenge
              dataset_path: /data/rsadhukh/eval_data/ai2_arc
            - task: race
              dataset_path: /data/rsadhukh/eval_data/race
            - task: mmlu
              dataset_path: /data/rsadhukh/eval_data/mmlu
            - task: gsm8k
              dataset_path: /data/rsadhukh/eval_data/gsm8k
            - task: mbpp
              dataset_path: /data/rsadhukh/eval_data/mbpp
            - task: humaneval
              dataset_path: /data/rsadhukh/eval_data/humaneval
        confirm_run_unsafe_code: true
        batch_size: 64
    validation: null