dump_dir: logs/debug
name: "olmo2_1B_midfine"
model_type: olmo3
steps: 50_000
probe_freq: 100
seed: 777
grad_acc_steps: 4

optim:
    scheduler: "linear"
    lr: 7.44e-5
    weight_decay: 0.1
    warmup: 0
    lr_min_ratio: 0.0
    clip: 1.0

distributed:
    fsdp_type: full_shard
    compile: true
    model_dtype: bf16
    matmul_allow_tf32: false
    selective_activation_checkpointing: false
    tp_size: 1

model:
    dim: 2048
    ffn_dim_multiplier: 1.5
    multiple_of: 256
    n_layers: 16
    n_heads: 16
    n_kv_heads: 16
    head_dim: 128
    weight_tying: false
    init_base_std: 0.02
    init_std_factor: disabled
    norm_eps: 1.0e-6
    max_seqlen: 4096
    vocab_size: 100352
    rope_theta: 500000.0
    rope_scaling: null

data:
    root_dir: data/dolmino-mix_shuffled
    sources:
        common_crawl-high-quality: 22.5
        cranecode: 8.39
        cranemath: 3.99
        dolmino-math: 12.29
        dolmino_1-flan: 6.12
        gemini-reasoning-traces: 0.12
        general_reasoning_mix: 1.0
        code-meta-reasoning: 0.546
        llama_nemotron-reasoning-traces: 3.968
        math-meta-reasoning: 0.546
        megamatt: 1.78
        nemotron-synth-qa: 4.38
        olmocr_science_pdfs: 1.78
        openthoughts2: 0.546
        program_verifiable: 0.22
        qwq-reasoning-traces: 0.546
        reddit_to_flashcards: 7.66
        stack_edu: 11.61
        stem-heavy-crawl: 8.22
        tulu-3-sft: 0.604
        wiki_to_rcqa: 1.24
    node_local: true
    batch_size: 16
    prefetch_size: 1024
    seq_len: 4096
    n_views: 2
    load_async: true
    add_bos: true
    add_eos: true
    tokenizer:
        name: huggingface
        path: /data/rsadhukh/checkpoints/olmo2-1b-base-token4T

profiling:
    run: true

checkpoint:
    # Student initialization checkpoint (typically prepared by prepare_stem_checkpoint.py)
    init_ckpt_path: /data/rsadhukh/checkpoints/olmo2-1b-base-token4T
    dump:
        every: 10000
        keep: 1
    eval:
        every: 10000
        keep: 1

logging:
    freq: 10
    wandb:
        project: "stem"
        name: "olmo2-1B-midfine"

eval:
    generator:
        max_tokens: 16384
        dtype: bf16
        temperature: 1.0
        top_p: 0.95
    harness:
        tasks:
            - task: hellaswag
              dataset_path: /data-fsx/beidchen-sandbox/data/eval_data/hellaswag
            - task: boolq
              dataset_path: /data-fsx/beidchen-sandbox/data/eval_data/super_glue
            - task: piqa
              dataset_path: /data-fsx/beidchen-sandbox/data/eval_data/piqa
            - task: winogrande
              dataset_path: /data-fsx/beidchen-sandbox/data/eval_data/winogrande
            - task: openbookqa
              dataset_path: /data-fsx/beidchen-sandbox/data/eval_data/openbookqa
            - task: arc_easy
              dataset_path: /data-fsx/beidchen-sandbox/data/eval_data/ai2_arc
            - task: arc_challenge
              dataset_path: /data-fsx/beidchen-sandbox/data/eval_data/ai2_arc
            - task: race
              dataset_path: /data-fsx/beidchen-sandbox/data/eval_data/race
            - task: mmlu
              dataset_path: /data-fsx/beidchen-sandbox/data/eval_data/mmlu
            - task: mbpp
              dataset_path: /data-fsx/beidchen-sandbox/data/eval_data/mbpp
        confirm_run_unsafe_code: true
        batch_size: 64
    validation:
        max_steps: 1000