name: "stem_eval"
dump_dir: logs/stem_eval
ckpt_dir: /raid/user_data/rsadhukh/checkpoints/STEM-1B-pretrain1T-midtrain100B-stem/
stem_parallel_size: 8  # must match training stem_parallel_size

generator:
    max_tokens: 32768
    dtype: bf16
    temperature: 0.0
    top_p: 0.95
    show_progress: true

harness:
    tasks:
        - task: hellaswag
          dataset_path: /data/rsadhukh/eval_data/hellaswag
        - task: boolq
          dataset_path: /data/rsadhukh/eval_data/super_glue
        - task: piqa
          dataset_path: /data/rsadhukh/eval_data/piqa
        - task: winogrande
          dataset_path: /data/rsadhukh/eval_data/winogrande
        - task: openbookqa
          dataset_path: /data/rsadhukh/eval_data/openbookqa
        - task: arc_easy
          dataset_path: /data/rsadhukh/eval_data/ai2_arc
        - task: arc_challenge
          dataset_path: /data/rsadhukh/eval_data/ai2_arc
        - task: race
          dataset_path: /data/rsadhukh/eval_data/race
        # - task: mmlu
        #   dataset_path: /data/rsadhukh/eval_data/mmlu
        # - task: gsm8k
        #   dataset_path: /data/rsadhukh/eval_data/gsm8k
        # - task: mbpp
        #   dataset_path: /data/rsadhukh/eval_data/mbpp
        # - task: humaneval
        #   dataset_path: /data/rsadhukh/eval_data/humaneval
        # - task: bbh
        #   dataset_path: /data/rsadhukh/eval_data/bbh
        # - task: coqa
        #   dataset_path: /data/rsadhukh/eval_data/coqa
    confirm_run_unsafe_code: true
    batch_size: 128
validation: null

