dump_dir: /raid/user_data/rsadhukh/logs/mobilellm_350M
name: stem_mobilellm_350M
steps: 400_000
probe_freq: null
seed: 777
grad_acc_steps: 4 

optim:
  lr: 2e-3
  weight_decay: 0.1
  warmup: 2000
  lr_min_ratio: 0.1
  clip: 1.0

distributed:
  fsdp_type: full_shard
  compile: true
  model_dtype: bf16
  matmul_allow_tf32: false
  selective_activation_checkpointing: false
  tp_size: 1

model:
  dim: 960
  ffn_dim_multiplier: null
  n_layers: 32
  n_heads: 15
  n_kv_heads: 5
  head_dim: 64
  weight_tying: True
  vocab_size: 32000
  init_base_std: 0.02
  init_std_factor: disabled
  max_seqlen: 4096
  rope_theta: 10000.0
  rope_scaling: null
  stem_layers: [2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26]

data:
  # root_dir: /raid/user_data/rsadhukh/data/
  root_dir: /raid/user_data/rsadhukh/
  sources:
    dclm-baseline_shuffled: 1.0
  batch_size: 32
  prefetch_size: 1024
  seq_len: 4096
  n_views: 2
  load_async: true
  add_bos: true
  add_eos: true
  tokenizer:
    name: sp
    # path: /sharedscratch/rsadhukh/checkpoints/MobileLLM-350M/tokenizer.model
    path: /raid/user_data/rsadhukh/checkpoints/MobileLLM-350M/tokenizer.model

profiling:
    run: true

checkpoint:
    dump:
        every: 5000
        keep: 1
    eval:
        every: 5000
        keep: 1

logging:
    freq: 10
    wandb:
        project: "stem"
        name: "mobilellm_350M"

eval:
    generator:
        max_tokens: 16384
        dtype: bf16
        temperature: 1.0
        top_p: 0.95
    harness:
        tasks:
            - task: hellaswag
              dataset_path: /raid/user_data/rsadhukh/test_data/hellaswag
            - task: boolq
              dataset_path: /raid/user_data/rsadhukh/test_data/super_glue
            - task: piqa
              dataset_path: /raid/user_data/rsadhukh/test_data/piqa
            - task: arc_easy
              dataset_path: /raid/user_data/rsadhukh/test_data/ai2_arc
            - task: arc_challenge
              dataset_path: /raid/user_data/rsadhukh/test_data/ai2_arc
            - task: openbookqa
              dataset_path: /raid/user_data/rsadhukh/test_data/openbookqa
            - task: winogrande
              dataset_path: /raid/user_data/rsadhukh/test_data/winogrande
            - task: race
              dataset_path: /raid/user_data/rsadhukh/test_data/race
    validation:
        max_steps: 100
