kubectl apply -f amyaml_submit/scripts/beidchen-dolm-prep-midfine0-211431.yaml
kubectl apply -f amyaml_submit/scripts/beidchen-dolm-prep-midfine1-211431.yaml
kubectl apply -f amyaml_submit/scripts/beidchen-dolm-prep-midfine10-211431.yaml
kubectl apply -f amyaml_submit/scripts/beidchen-dolm-prep-midfine11-211431.yaml
kubectl apply -f amyaml_submit/scripts/beidchen-dolm-prep-midfine12-211431.yaml
kubectl apply -f amyaml_submit/scripts/beidchen-dolm-prep-midfine13-211431.yaml
kubectl apply -f amyaml_submit/scripts/beidchen-dolm-prep-midfine14-211431.yaml
kubectl apply -f amyaml_submit/scripts/beidchen-dolm-prep-midfine15-211431.yaml
kubectl apply -f amyaml_submit/scripts/beidchen-dolm-prep-midfine2-211431.yaml
kubectl apply -f amyaml_submit/scripts/beidchen-dolm-prep-midfine3-211431.yaml
kubectl apply -f amyaml_submit/scripts/beidchen-dolm-prep-midfine4-211431.yaml
kubectl apply -f amyaml_submit/scripts/beidchen-dolm-prep-midfine5-211431.yaml
kubectl apply -f amyaml_submit/scripts/beidchen-dolm-prep-midfine6-211431.yaml
kubectl apply -f amyaml_submit/scripts/beidchen-dolm-prep-midfine7-211431.yaml
kubectl apply -f amyaml_submit/scripts/beidchen-dolm-prep-midfine8-211431.yaml
kubectl apply -f amyaml_submit/scripts/beidchen-dolm-prep-midfine9-211431.yaml
